<?php
$config['protocol']='smtp';
$config['smtp_host']='smtp.gmail.com';
$config['smtp_port']='465';
$config['smtp_timeout']='30';
$config['smtp_user']='braxtondiggs@gmail.com';
$config['smtp_pass']='Blackbad882003';
$config['charset']='utf-8';
$config['newline']="\r\n";