<?php
$config['protocol']='smtp';
$config['smtp_host']='ssl://mail.cymbit.com';
$config['smtp_port']='465';
$config['smtp_timeout']='30';
$config['smtp_user']='admin@cymbit.com';
$config['smtp_pass']='Blackbad882003';
$config['charset']='utf-8';
$config['newline']="\r\n";